### ISSUE TITLE
Error for the second block

### ISSUE THREAD

**Issue by hasan-sayeed** [AhmedNazir/eBanglaLibrary#1]
I'm getting an error for the 2nd block of code.
![bb](https://user-images.githubusercontent.com/47003757/160526286-6ff5fd05-d7f2-4fec-8627-dd9e5a15b0f4.PNG)

**Comment by AhmedNazir** [comment]
ebanglaLibrary has updated their UI. Now this script is not working properly.

**Comment by AhmedNazir** [comment]
Book Name ?
URL?

**Comment by hasan-sayeed** [comment]
Book Name: তিতাস একটি নদীর নাম
URL: https://www.ebanglalibrary.com/2507/%e0%a6%a4%e0%a6%bf%e0%a6%a4%e0%a6%be%e0%a6%b8-%e0%a6%8f%e0%a6%95%e0%a6%9f%e0%a6%bf-%e0%a6%a8%e0%a6%a6%e0%a7%80%e0%a6%b0-%e0%a6%a8%e0%a6%be%e0%a6%ae/

**Comment by hasan-sayeed** [comment]
It worked! Thank you so much!!
