### ISSUE TITLE
Google Collab keeps Connecting but never connects

### ISSUE THREAD

**Issue by rahaaatul** [AhmedNazir/eBanglaLibrary#2]
As the title says, it shows connecting, allocating, and repeating the same thing over and over again.

**Comment by AhmedNazir** [comment]
I have tried and I am not facing these kinds of problems. 
This is a Google Colab problem and it's beyond my scope.

My suggestion is that:
Try again after some time.

**Comment by rahaaatul** [comment]
> I have tried and I am not facing these kinds of problems.  This is a Google Colab problem and it's beyond my scope.
> 
> My suggestion is that: Try again after some time.

I will, but can I request you to make your code run in termux? That'd be awesome for android users to use, easily.

**Comment by AhmedNazir** [comment]
I have no experience of termux.
I think, the codes of this project can not run on termux on android.

It needs some image manipulation for cover picture. It needs to download lots of library.

Google Colab is more powerful than Termux on Android.
